
volumes:
  dbdata:

services:
  db:
    image: "asset-docs-postgres-db:latest"
    build:
      context:    .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: "asset_docs"
      POSTGRES_USER: "asset_docs"
      POSTGRES_PASSWORD: "asset_docs"
    ports:
     - 2345:5432
    # Don't create a persistent volume (for development). Instead, init the
    # postgres database every time.
    tmpfs:
      - "/var/lib/postgresql/data"
    volumes:
      - "./initdb.sh:/docker-entrypoint-initdb.d/99_initdb.sh:ro"
